name: segmentation-streamlit
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jupyterlab=4.3.4
  - matplotlib=3.9.2
  - opencv=4.10.0
  - pandas=2.2.3
  - pip
  - python=3.9
  - scikit-image=0.24.0
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pip:
      - numpy<2.0
      - tensorflow==2.10
      - tensorboard==2.10.1
      - tensorflow-datasets==4.8.3
      - tensorflow-hub==0.16.1
      - streamlit